name: ci

on: [push]

jobs:
  fern-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Fern
        run:  npm install -g fern-api

      - name: Check Fern API is valid
        run: fern check

  fern-release: 
    needs: fern-check
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
      
      - name: Download Fern
        run: npm install -g fern-api

      - name: Release SDKs
        env:
          FERN_NPM_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}
          FERN_MAVEN_USERNAME: ${{ secrets.FERN_MAVEN_USERNAME }}
          FERN_MAVEN_TOKEN: ${{ secrets.FERN_MAVEN_TOKEN }}
        run: fern release ${{ github.ref_name }} --log-level debug
        
