name: ci

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install Fern
        run: npm install -g fern-api
      
      - name: Release Fern
        run: echo ${{ github.event.release.tag_name }}